### Snippets for Jupyter/Google Colab Notebooks 
# Thank you! Cristobal Missana

### Librerías Básicas
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

from scipy import stats

### Conectar con Google Drive
from google.colab import drive
drive.mount('/content/drive/')

ruta = "/content/drive/My Drive/"
df = pd.read_csv(ruta)

### Análisis Exploratorio
df.info()
df.describe()
df.stats.skew()
df.stats.kurtosis()

### Generar subplots
fig, ax = plt.subplots(nrows=n, ncols=m)
plt.plot(df[""], ax=[0, 0]) # Primero
plt.plot(df[""], ax=[n-1, m-1]) # Último

plt.hist(df[''], bins=15, density=True)
plt.title("")
plt.grid(axis='y') # Genera líneas horizontales
plt.show()

plt.boxplot(df[''])
plt.title("")
plt.show()

sns.heatmap(df.corr(numeric_only=True), annot=True)
plt.show()

### Heatmap con figsize modificable
fig, ax = plt.subplots(figsize=(20,10))
sns.heatmap(df.corr(numeric_only=True), annot=True, linewidths=.5, ax=ax)
plt.show()

### Librerías Análisis Inferencial
from scipy.stats import fit, goodness_of_fit, ks_1samp

loc, scale = dist_func.fit(df[''])
cdf = stats.dist_func(loc, scale).cdf

ks = ks_1samp(df[''], cdf)
if ks.pvalue > confianza:
    print("No se rechaza la hipótesis nula.")
else:
    print("Se rechaza la hipótesis nula.")

### Train/Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train_, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

### Reducción de Dimensionalidad
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler


# Estandarizar las características
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)


### Paleta de colores
# Catppuccin Mocha
colors = ['#f5e0dc', '#f2cdcd', '#f5c2e7', '#cba6f7', '#f38ba8', '#eba0ac',
          '#fab387', '#f9e2af', '#a6e3a1', '#94e2d5', '#89dceb', '#74c7ec',
          '#89b4fa', '#b4befe', '#cdd6f4', '#bac2de', '#a6adc8', '#9399b2',
          '#7f849c', '#6c7086', '#585b70', '#45475a', '#313244', '#1e1e2e',
          '#181825', '#11111b']
sns.set_palette(colors, n_colors=len(colors))

# ----------------------------------------


"""
<p align="center">
  <img src="https://www.inf.ucv.cl/wp-content/themes/escuelainformaticapucv/img/logo_smaller-01.png" alt="Logo" width="400" height="100"/>
</p>

 <p align="center"> <font color="white"><u> Título </u> </font> </p>


<p align="center">  Nombre </p>
<p align="center">  Fecha </p>
"""


"""snippets.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mKTyiucTd18VoeXf6mivGW1Y12MhE8y4
"""